# Задания по NumPy
В данной тетради вам необходимо выполнить несколько задач по NumPy. Для некоторых задач необходимо найти подходящие функции в документации NumPy. Вы можете пользоваться поиском в интернете для этого. Задания необходимо выполнить без использования циклов с помощью векторизованых вычислений.

Для начала симпортируйте библиотеку `numpy` с алиасом `np`

In [1]:
import numpy as np

#### 1. Создайте массив целых чисел от 1 до 10 включительно

In [6]:
a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


#### 2. Вычислите факториал для каждого числа массива целых чисел от 1 до 10 включительно  с помощью функции NumPy (подсказкаЖ воспользуйтесь одной из кумулятивных функций)

In [11]:
np.cumprod(a)

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800])

#### 3. Создайте массив целых чисел от 1 до 10 включительно и затем переверните этот массив с помощью срезов (slices)

In [28]:
x = np.arange(1,10+1)
x[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

#### 4. Создайте массив целых чисел от -10 до 10 включительно и вычислите отдельно сумму отрицательных и положительных чисел используя булевые маски

In [41]:
x = np.arange(-10,11)
print(np.sum(x[x>0]))
print(np.sum(x[x<0]))

55
-55


####  5. Создайте массив случайных целых чисел от 1 до 100 размером 5 x 5 и найдите минимум, максимум и среднее значение массива

In [78]:
x = np.random.randint(1, 100, size=[5,5])
print('Max:',np.max(x))
print('Min:',np.min(x))
print('Avg:',np.average(x))

Max: 94
Min: 14
Avg: 56.76


####  6. В следующих трех задачах необходимо нормализовать строки двухмерного массива. Для начала создайте массив от 1 до 25 включительно размером 5 x 5

In [98]:
x = np.arange(1,25+1).reshape(5,5)

####  7. Вычислите минимум и максимум каждой строки массива. В результате у вас должны получиться два массива размера 5. С помощью функции `reshape` переверните эти два массива, чтобы получить массив в столбец размером 5 x 1
```python
min = [[ 0],
       [ 5],
       [10],
       [15],
       [20]]

max = [[ 4],
       [ 9],
       [14],
       [19],
       [24]]
```

In [104]:
min = np.min(x, axis=1).reshape(5,1)
print('min = ', min)

min =  [[ 1]
 [ 6]
 [11]
 [16]
 [21]]


In [103]:
max = np.max(x, axis=1).reshape(5,1)
print('max = ', max)

max =  [[ 5]
 [10]
 [15]
 [20]
 [25]]


####  8. Нормализуйте каждую строку массива из предыдущей задачи используя вычисленные минимумы и максимумы строк. Для нормализации необходимо вычесть из каждой строки её минимум и результат поделить на максимум каждой строки
$$
normalized = \frac{x - min}{max}
$$

In [109]:
(x-np.min(x,axis=1).reshape(5,1))/np.max(x, axis=1).reshape(5,1)

array([[ 0.        ,  0.2       ,  0.4       ,  0.6       ,  0.8       ],
       [ 0.        ,  0.1       ,  0.2       ,  0.3       ,  0.4       ],
       [ 0.        ,  0.06666667,  0.13333333,  0.2       ,  0.26666667],
       [ 0.        ,  0.05      ,  0.1       ,  0.15      ,  0.2       ],
       [ 0.        ,  0.04      ,  0.08      ,  0.12      ,  0.16      ]])

####  9. Создайте массив случайных целых чисел от 0 до 100 размером 10. Замените минимальный элемент этого массива на 0 и максимальный на 100. Вам необходимо использовать функцию, которая возвращает аргумент минимального и максимального элементов

In [126]:
x=np.random.randint(0, 100, 10)
print('before:',x)
print('min index:',np.argmin(x))
print('max index:',np.argmax(x))
x[np.argmin(x)] = 0
x[np.argmax(x)] = 100
print('after:',x)

before: [99 29 21 33 12 48 93 68 92 23]
min index: 4
max index: 0
after: [100  29  21  33   0  48  93  68  92  23]


#### 10. Допустим у нас есть двухмерных массив, который содержит координаты двух точек в декартовой системе координат. Вычислите расстояние между этими точками с помощью теоремы пифагора.
$$
\begin{align}
P &= \begin{bmatrix}
        x_1 & y_1\\
        x_2 & y_2
     \end{bmatrix}
\end{align} \\
Distance = \sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}
$$
Необходимо выполнить данное задание с помощью векторизованных вычислений без циклов

In [132]:
p = np.array([[1, 1],  # x1, y1
              [4, 5]]) # x2, y2
d = np.sqrt(np.square(p[1][0]-p[0][0])+np.square(p[1][1]-p[0][1]))
d

5.0

#### 11. Создайте массив от -2 до 3 включительно и вычислите следующее выражение
$$
\frac{1}{1 + e^{-(a_0 + a_1 + \cdots + a_5)}}
$$
Для вычисления $e^x$ используйте функцию `np.exp`

In [139]:
1/(1+np.exp(-np.sum(np.arange(-1,3+1))))

0.99330714907571527